### ISSUE TITLE
[CREPS] Version non à jour sur Hyblab.fr

### ISSUE THREAD

**Issue by antoinechalifour** [mperreir/DataSport2015#6]
La version sur Hyblab.fr du site du creps n'est pas à jour, il y a des caractères chinois à la places des icônes H/F. Un petit git pull pourrait régler ça !

**Comment by mperreir** [comment]
Le pull a été fait. J'ai juste oublié de mettre à jour le serveur via FTP. Ca va venir dans la journée.
